import type { Phrase } from './content'

/** Sample deck so flashcards, matching, and fill-in-the-blank work before any capture. */
const PHRASES: Phrase[] = [
  {
    id: 'mock-nocap',
    term: '노캡',
    reading: 'no-kaep',
    lang: 'ko',
    partOfSpeech: 'slang',
    tags: ['casual', 'internet slang', 'emphasis'],
    definition: '“No cap.” It means “I’m not lying” or “for real.”',
    contextMeaning: 'In a comment under a story, 노캡 is the writer swearing the thing they just said actually happened.',
    tone: 'Casual and a little showy. Friends use it in texts and comments. It would sound odd in a formal message.',
    examples: [
      { text: '노캡, 그 카페 줄이 두 시간이야.', gloss: 'No cap, the line at that cafe is two hours.' },
      { text: '노캡으로 말하는 건데 진짜 맛있어.', gloss: 'I’m not lying — it’s actually good.' },
    ],
    followUps: [
      { q: 'Is this the same as 진짜?', a: '진짜 means “really.” 노캡 is the slangy way to say you are not exaggerating, borrowed from English “no cap.”' },
    ],
    shortMeaning: 'I’m not lying',
    cloze: { sentence: '___ , 어제 콘서트 진짜 미쳤어.', answer: '노캡' },
    source: { app: 'Instagram', handle: '@minji', text: '노캡, 어제 콘서트 진짜 미쳤어.' },
  },
  {
    id: 'mock-fire',
    term: '쩐다',
    reading: 'jjeon-da',
    lang: 'ko',
    partOfSpeech: 'slang',
    tags: ['casual', 'praise', 'internet slang'],
    definition: '“That’s fire.” It means something is so cool you can barely believe it.',
    contextMeaning: 'Under a fit check, 쩐다 is a strong compliment: the outfit looks incredible.',
    tone: 'Very casual praise between friends. 개쩐다 is even stronger. Too blunt for anyone you speak politely to.',
    examples: [
      { text: '이 재킷 진짜 쩐다.', gloss: 'This jacket is fire.' },
      { text: '새 노래 쩐다, 바로 저장함.', gloss: 'The new song is so cool, I saved it immediately.' },
    ],
    followUps: [
      { q: 'How is this different from 대박?', a: '대박 is general amazement. 쩐다 specifically means something looks or sounds extremely cool.' },
    ],
    shortMeaning: 'That’s so cool',
    cloze: { sentence: '오늘 코디 완전 ___.', answer: '쩐다' },
    source: { app: 'TikTok', handle: '@stylelog', text: '오늘 코디 완전 쩐다.' },
  },
  {
    id: 'mock-daebak',
    term: '대박',
    reading: 'dae-bak',
    lang: 'ko',
    partOfSpeech: 'slang',
    tags: ['casual', 'reaction'],
    definition: 'A burst of “whoa” or “that’s amazing.” It started as “jackpot.”',
    contextMeaning: 'Replying to a score screenshot, 대박 is pure surprise that it went that well.',
    tone: 'Friendly and common across ages now, though it still feels spoken rather than written in anything formal.',
    examples: [
      { text: '대박, 너 합격했어?', gloss: 'Whoa, you got in?' },
      { text: '이번 드라마 결말 대박이다.', gloss: 'The ending of this drama is incredible.' },
    ],
    followUps: [
      { q: 'Can it be negative?', a: 'Usually it is impressed. 대박 사고 means a huge mess, so the size of the reaction depends on what follows.' },
    ],
    shortMeaning: 'Whoa, amazing',
    cloze: { sentence: '시험 1등 했다니 ___.', answer: '대박' },
    source: { app: 'KakaoTalk', handle: '수진', text: '시험 1등 했다니 대박.' },
  },
  {
    id: 'mock-heol',
    term: '헐',
    reading: 'heol',
    lang: 'ko',
    partOfSpeech: 'interjection',
    tags: ['casual', 'reaction'],
    definition: '“No way.” A sharp little gasp when something is shocking or unbelievable.',
    contextMeaning: 'It is the first reaction to gossip, before any real opinion.',
    tone: 'Soft and spoken. Fine with friends. In a serious conversation it can sound like you are not taking it seriously.',
    examples: [
      { text: '헐, 그게 사실이야?', gloss: 'No way, is that true?' },
      { text: '헐 대박 실화냐.', gloss: 'Whoa, is this actually real?' },
    ],
    followUps: [
      { q: 'Is 헐 a word?', a: 'It is a sound people spell out, like “huh,” more than a dictionary word.' },
    ],
    shortMeaning: 'No way',
    cloze: { sentence: '___, 둘이 사귄다고?', answer: '헐' },
    source: { app: 'KakaoTalk', handle: '준호', text: '헐, 둘이 사귄다고?' },
  },
  {
    id: 'mock-injeong',
    term: '인정',
    reading: 'in-jeong',
    lang: 'ko',
    partOfSpeech: 'slang',
    tags: ['casual', 'agreement'],
    definition: '“Facts.” You are admitting the other person is right.',
    contextMeaning: 'Dropped on its own under a take, it means “I can’t argue with that.”',
    tone: 'Casual agreement. The plain word also means “acknowledge,” but alone in a chat it is the slang reaction.',
    examples: [
      { text: '그 말은 인정.', gloss: 'That point? Facts.' },
      { text: '맛은 인정하는데 비싸다.', gloss: 'The taste is legit, but it’s expensive.' },
    ],
    followUps: [
      { q: 'Is it the same as 맞아?', a: '맞아 is a plain “right.” 인정 feels like you are conceding a point you might have doubted.' },
    ],
    shortMeaning: 'Facts, I agree',
    cloze: { sentence: '이 부분만큼은 ___.', answer: '인정' },
    source: { app: 'YouTube', handle: '댓글', text: '이 부분만큼은 인정.' },
  },
  {
    id: 'mock-legend',
    term: '레전드',
    reading: 're-jeon-deu',
    lang: 'ko',
    partOfSpeech: 'slang',
    tags: ['casual', 'internet slang', 'praise'],
    definition: '“Legendary.” Something so good or so chaotic that people will keep bringing it up.',
    contextMeaning: 'On a highlight clip, 레전드 means this moment belongs in the hall of fame.',
    tone: 'Playful hype. It can praise or roast: a legendary fail is still 레전드.',
    examples: [
      { text: '어제 경기 마지막 골 레전드였다.', gloss: 'The last goal last night was legendary.' },
      { text: '그 방송 사고는 레전드로 남음.', gloss: 'That on-air mess is going to stay legendary.' },
    ],
    followUps: [
      { q: 'Is this just the English word?', a: 'Yes, from “legend,” but in Korean chat it is its own reaction word, not a description of a historical person.' },
    ],
    shortMeaning: 'Legendary',
    cloze: { sentence: '마지막 장면은 진짜 ___.', answer: '레전드' },
    source: { app: 'YouTube', handle: '하이라이트', text: '마지막 장면은 진짜 레전드.' },
  },
  {
    id: 'mock-kk',
    term: 'ㅋㅋ',
    reading: 'keu-keu',
    lang: 'ko',
    partOfSpeech: 'slang',
    tags: ['casual', 'texting'],
    definition: 'Laughter, like “lol” or “haha.” Each extra ㅋ is a bigger laugh.',
    contextMeaning: 'Two ㅋ is a small, polite chuckle. A long string is actually cracking up.',
    tone: 'The default way to laugh in chat. In a serious thread, even one ㅋ can sound like you are brushing the person off.',
    examples: [
      { text: 'ㅋㅋ 그건 좀 심했다.', gloss: 'Lol that was a bit much.' },
      { text: 'ㅋㅋㅋㅋ 배 아프다.', gloss: 'Hahaha my stomach hurts.' },
    ],
    followUps: [
      { q: 'What about ㅎㅎ?', a: 'ㅎㅎ is a softer, warmer laugh. ㅋㅋ is closer to “lol” and can be drier.' },
    ],
    shortMeaning: 'lol',
    cloze: { sentence: '그 밈 보고 ___ 밖에 안 나옴.', answer: 'ㅋㅋ' },
    source: { app: 'KakaoTalk', handle: '민재', text: '그 밈 보고 ㅋㅋ 밖에 안 나옴.' },
  },
  {
    id: 'mock-gaekkul',
    term: '개꿀',
    reading: 'gae-kkul',
    lang: 'ko',
    partOfSpeech: 'slang',
    tags: ['casual', 'internet slang'],
    definition: '“So sweet” or “what a steal.” A situation that works out ridiculously well for you.',
    contextMeaning: 'About a shift that ended early, 개꿀 means this is an unfairly good deal and they are happy about it.',
    tone: 'Blunt slang. 개 intensifies, and it is rude around anyone you are being polite with.',
    examples: [
      { text: '오늘 수업 휴강이라 개꿀.', gloss: 'Class got cancelled today, what a steal.' },
      { text: '무료 배송에 쿠폰까지 개꿀이네.', gloss: 'Free shipping plus a coupon — too good.' },
    ],
    followUps: [
      { q: 'Why does it start with 개?', a: '개 is a crude intensifier, like “hella.” It makes 꿀, “honey,” mean “absurdly sweet.”' },
    ],
    shortMeaning: 'What a steal',
    cloze: { sentence: '칼퇴에 보너스까지 ___.', answer: '개꿀' },
    source: { app: 'X', handle: '@worklog', text: '칼퇴에 보너스까지 개꿀.' },
  },
]

const STATS: { daysAgo: number; mastery: number; attempts: number; misses: number }[] = [
  { daysAgo: 1, mastery: 0.2, attempts: 4, misses: 3 },
  { daysAgo: 1, mastery: 0.35, attempts: 3, misses: 2 },
  { daysAgo: 2, mastery: 0.5, attempts: 4, misses: 2 },
  { daysAgo: 3, mastery: 0.15, attempts: 2, misses: 2 },
  { daysAgo: 4, mastery: 0.7, attempts: 5, misses: 1 },
  { daysAgo: 5, mastery: 0.4, attempts: 3, misses: 1 },
  { daysAgo: 6, mastery: 0.85, attempts: 6, misses: 0 },
  { daysAgo: 8, mastery: 0.55, attempts: 4, misses: 1 },
]

export const MOCK_DECK: { phrase: Phrase; daysAgo: number; mastery: number; attempts: number; misses: number }[] = PHRASES.map(
  (phrase, i) => ({ phrase, ...STATS[i] }),
)
